name: Fetch and Upload Data

on:
  schedule:
    - cron: "0 0,2,4,6,8,10,12,14,16,18,20 * * *"
  # 如果需要手动触发，可以取消注释下面的部分
  workflow_dispatch:

jobs:
  fetch_and_upload_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install axios and mysql
      run: npm install axios mysql

    - name: Fetch Data and Upload to Database
      run: node fetch-and-upload.js
