
name: Periodic Data Fetch and Save
on:
  schedule:
    - cron: '0 */2 8-22 * *'

  workflow_dispatch: # 允许手动触发执行
    inputs:
      manual_run:
        description: 'Trigger a manual run'
        default: 'true'


jobs:
  fetch-and-store-data:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch data from API
        run: |
          mkdir -p data
          if curl -sSf https://physics-api-cn.turtlesim.com/Users > data/$(date +'%Y-%m-%d-%H%M%S').json; then
            echo "Data fetched successfully."
          else
            echo "Failed to fetch data from API."
            exit 1
          fi

      - name: Switch to Git repository directory
        run: cd ${{ github.workspace }}

      - name: Set Git user configuration
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Add data file to git
        run: |
          if [ "$(ls -A data/*.json)" ]; then
            git add data/*.json
          else
            echo "No data files found. Skipping git add."
          fi

      - name: Commit and push changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit. Skipping git commit and push."
          else
            git commit -m "Automated data update" -a
            git push origin main
          fi
